import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, FlatList, TouchableOpacity, Image, ActivityIndicator, TextInput } from 'react-native';
import { Feather } from '@expo/vector-icons';

const COLORS = {
  bg: '#e6e0d4',
  surface: '#FFFFFF',
  white: '#FFFFFF',
  primary: '#4a3b2c',
  primaryHover: '#2b2118',
  primaryLight: '#d5cbb8',
  textDark: '#0a0a0a',
  textLight: '#736150',
  border: '#d5cbb8',
  success: '#4a3b2c',
  warning: '#736150',
  danger: '#2b2118',
  error: '#2b2118',
};

import AsyncStorage from '@react-native-async-storage/async-storage';
import ApiService from '../services/ApiService';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

const GlobalHeader = ({ onMenuPress }) => (
  <View style={styles.headerContainer}>
    <TouchableOpacity style={styles.headerBtn} onPress={onMenuPress}>
      <Feather name="menu" size={20} color={COLORS.textDark} />
    </TouchableOpacity>
    <View style={styles.headerCenter}>
      <Text style={styles.headerTitle}>TagSnap</Text>
      <Text style={styles.headerSubtitle}>Estate Sale: All Estates</Text>
    </View>
    <TouchableOpacity style={styles.headerUserBtn}>
      <View style={styles.onlineDot} />
      <Feather name="users" size={16} color={COLORS.primary} />
    </TouchableOpacity>
  </View>
);

export default function CatalogScreen({ openDrawer }) {
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');

  useEffect(() => {
    fetchItems();
  }, []);

  const fetchItems = async () => {
    setLoading(true);
    try {
      const userId = await AsyncStorage.getItem('user_id');
      if (userId) {
        const data = await ApiService.getUserItems(userId);
        setItems(data || []);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  const handleExportPDF = async () => {
    try {
      let rows = items.map(item => `
        <tr>
          <td style="border: 1px solid #d5cbb8; padding: 12px; color: #0a0a0a;">${item.ai_title || item.title || item.name || 'Unknown Item'}</td>
          <td style="border: 1px solid #d5cbb8; padding: 12px; color: #4a3b2c; font-weight: bold;">$${item.estimated_min_price || 0} - $${item.estimated_max_price || 0}</td>
          <td style="border: 1px solid #d5cbb8; padding: 12px; color: #736150; font-size: 12px;">${item.ai_description || item.description || 'No description'}</td>
        </tr>
      `).join('');
      
      const html = `
        <html>
          <body style="font-family: Helvetica, Arial, sans-serif; padding: 40px; color: #2b2118;">
            <h1 style="color: #4a3b2c;">TagSnap Complete Catalog Export</h1>
            <hr style="border: 1px solid #d5cbb8; margin-bottom: 20px;" />
            <table style="width: 100%; border-collapse: collapse;">
              <tr style="background-color: #e6e0d4;">
                <th style="border: 1px solid #d5cbb8; padding: 12px; text-align: left; color: #2b2118;">Item Title</th>
                <th style="border: 1px solid #d5cbb8; padding: 12px; text-align: left; color: #2b2118;">Estimated Price</th>
                <th style="border: 1px solid #d5cbb8; padding: 12px; text-align: left; color: #2b2118;">Description</th>
              </tr>
              ${rows}
            </table>
            <p style="margin-top: 40px; font-size: 12px; color: #736150;">Generated by TagSnap App</p>
          </body>
        </html>
      `;
      const { uri } = await Print.printToFileAsync({ html });
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(uri);
      }
    } catch (e) {
      console.error('Export PDF Error:', e);
    }
  };

  const renderItem = ({ item }) => {
    const price = item.estimated_min_price 
      ? `${item.estimated_min_price}${item.estimated_max_price ? `-${item.estimated_max_price}` : ''}`
      : '-';

    return (
      <View style={styles.card}>
        <View style={styles.imageWrap}>
          {item.image_url ? (
            <Image source={{ uri: item.image_url }} style={styles.image} />
          ) : (
            <View style={styles.placeholder}>
              <Feather name="image" size={24} color="#94A3B8" />
            </View>
          )}
          <View style={styles.priceBadge}>
            <Text style={styles.priceText}>${price}</Text>
          </View>
        </View>
        <View style={styles.info}>
          <Text style={styles.title} numberOfLines={1}>{item.ai_title || item.title || item.name || 'Unknown Item'}</Text>
          <Text style={styles.subtitle} numberOfLines={1}>{item.category || 'Uncategorized'}</Text>
        </View>
      </View>
    );
  };

  return (
    <View style={styles.screen}>
      <GlobalHeader onMenuPress={openDrawer} />
      <View style={styles.content}>
        <View style={styles.sectionHeader}>
          <Text style={styles.sectionTitle}>All Catalog</Text>
          <TouchableOpacity style={styles.exportBtn} onPress={handleExportPDF}>
            <Text style={styles.exportText}>Export</Text>
          </TouchableOpacity>
        </View>

        <View style={{ flexDirection: 'row', marginBottom: 20, alignItems: 'center', backgroundColor: COLORS.surface, borderRadius: 12, paddingHorizontal: 14, borderWidth: 1, borderColor: COLORS.border }}>
          <Feather name="search" size={18} color="#94A3B8" />
          <TextInput 
            style={{ flex: 1, paddingVertical: 12, paddingLeft: 10, fontSize: 14, color: COLORS.textDark }}
            placeholder="Search items..."
            placeholderTextColor="#94A3B8"
            value={searchQuery}
            onChangeText={setSearchQuery}
          />
        </View>
        
        {loading ? (
          <ActivityIndicator size="large" color={COLORS.primary} style={{ marginTop: 40 }} />
        ) : (
          <FlatList
            data={items.filter(i => (i.ai_title || i.title || i.name || '').toLowerCase().includes(searchQuery.toLowerCase()))}
            keyExtractor={item => item.id?.toString() || Math.random().toString()}
            renderItem={renderItem}
            numColumns={2}
            columnWrapperStyle={styles.row}
            contentContainerStyle={styles.list}
            showsVerticalScrollIndicator={false}
            ListEmptyComponent={
              <View style={{ alignItems: 'center', marginTop: 60 }}>
                <Feather name="box" size={48} color="#CBD5E1" style={{ marginBottom: 16 }} />
                <Text style={{ fontSize: 18, fontWeight: '700', color: COLORS.textDark, marginBottom: 8 }}>No items yet</Text>
                <Text style={{ fontSize: 14, color: COLORS.textLight, textAlign: 'center' }}>Scan items to build your catalog.</Text>
              </View>
            }
          />
        )}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: COLORS.bg },
  content: { flex: 1, paddingHorizontal: 20 },
  
  headerContainer: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 20, paddingTop: 60, paddingBottom: 16,
    backgroundColor: COLORS.bg, borderBottomWidth: 1, borderBottomColor: COLORS.border,
  },
  headerBtn: { width: 40, height: 40, borderRadius: 20, borderWidth: 1, borderColor: COLORS.border, justifyContent: 'center', alignItems: 'center', backgroundColor: COLORS.surface },
  headerCenter: { alignItems: 'center' },
  headerTitle: { fontSize: 18, fontWeight: '800', color: COLORS.textDark, letterSpacing: -0.5 },
  headerSubtitle: { fontSize: 11, color: COLORS.textLight, marginTop: 2, fontWeight: '500' },
  headerUserBtn: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 20, backgroundColor: '#EFF6FF', borderWidth: 1, borderColor: '#BFDBFE' },
  onlineDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: COLORS.primary, marginRight: 6 },

  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 24, marginBottom: 16 },
  sectionTitle: { fontSize: 22, fontWeight: '800', color: COLORS.textDark, letterSpacing: -0.5 },
  exportBtn: { backgroundColor: '#DBEAFE', paddingHorizontal: 16, paddingVertical: 8, borderRadius: 12 },
  exportText: { color: COLORS.primary, fontSize: 12, fontWeight: '700' },

  list: { paddingBottom: 40 },
  row: { justifyContent: 'space-between', gap: 16, marginBottom: 16 },
  card: { flex: 1, backgroundColor: COLORS.surface, borderRadius: 16, overflow: 'hidden', borderWidth: 1, borderColor: COLORS.border },
  imageWrap: { width: '100%', aspectRatio: 1, backgroundColor: '#F8FAFC' },
  image: { width: '100%', height: '100%', resizeMode: 'cover' },
  placeholder: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  priceBadge: { position: 'absolute', top: 12, right: 12, backgroundColor: 'rgba(0,0,0,0.6)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12 },
  priceText: { color: '#FFF', fontSize: 10, fontWeight: '800' },
  info: { padding: 12 },
  title: { fontSize: 13, fontWeight: '800', color: COLORS.textDark, marginBottom: 4 },
  subtitle: { fontSize: 11, color: COLORS.textLight, fontWeight: '500' },
});
