import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, TouchableOpacity } from 'react-native';
import { Feather } from '@expo/vector-icons';

const COLORS = {
  bg: '#e6e0d4',
  surface: '#FFFFFF',
  white: '#FFFFFF',
  primary: '#4a3b2c',
  primaryHover: '#2b2118',
  primaryLight: '#d5cbb8',
  textDark: '#0a0a0a',
  textLight: '#736150',
  border: '#d5cbb8',
  success: '#4a3b2c',
  warning: '#736150',
  danger: '#2b2118',
  error: '#2b2118',
};

import AsyncStorage from '@react-native-async-storage/async-storage';
import ApiService from '../services/ApiService';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

const GlobalHeader = ({ onMenuPress }) => (
  <View style={styles.headerContainer}>
    <TouchableOpacity style={styles.headerBtn} onPress={onMenuPress}>
      <Feather name="menu" size={20} color={COLORS.textDark} />
    </TouchableOpacity>
    <View style={styles.headerCenter}>
      <Text style={styles.headerTitle}>TagSnap</Text>
      <Text style={styles.headerSubtitle}>Estate Sale: All Estates</Text>
    </View>
    <TouchableOpacity style={styles.headerUserBtn}>
      <View style={styles.onlineDot} />
      <Feather name="users" size={16} color={COLORS.primary} />
    </TouchableOpacity>
  </View>
);

export default function ReportsScreen({ openDrawer }) {
  const [downloading, setDownloading] = useState(false);
  const [totalValuation, setTotalValuation] = useState(0);
  const [itemsCount, setItemsCount] = useState(0);
  const [estatesCount, setEstatesCount] = useState(0);

  useEffect(() => {
    fetchAnalytics();
  }, []);

  const fetchAnalytics = async () => {
    try {
      const userId = await AsyncStorage.getItem('user_id');
      if (userId) {
        const [items, estates] = await Promise.all([
          ApiService.getUserItems(userId),
          ApiService.getUserEstates(userId)
        ]);
        
        let valuation = 0;
        (items || []).forEach(item => {
          if (item.estimated_max_price) valuation += item.estimated_max_price;
          else if (item.estimated_min_price) valuation += item.estimated_min_price;
        });

        setTotalValuation(valuation);
        setItemsCount((items || []).length);
        setEstatesCount((estates || []).length);
      }
    } catch (e) {
      console.error(e);
    }
  };

  const handleDownloadPDF = async () => {
    try {
      const html = `
        <html>
          <body style="font-family: Helvetica, Arial, sans-serif; padding: 40px; color: #2b2118;">
            <h1 style="color: #4a3b2c;">TagSnap Inventory Analytics</h1>
            <hr style="border: 1px solid #d5cbb8; margin-bottom: 20px;" />
            <h2>Overview</h2>
            <p style="font-size: 18px;"><strong>Total Valuation:</strong> $${totalValuation.toLocaleString()}</p>
            <p style="font-size: 18px;"><strong>Total Items Scanned:</strong> ${itemsCount}</p>
            <p style="font-size: 18px;"><strong>Total Estates:</strong> ${estatesCount}</p>
            <p style="margin-top: 40px; font-size: 12px; color: #736150;">Generated by TagSnap App</p>
          </body>
        </html>
      `;
      const { uri } = await Print.printToFileAsync({ html });
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(uri);
      }
    } catch (e) {
      console.error('PDF Error:', e);
    }
  };

  return (
    <View style={styles.screen}>
      <GlobalHeader onMenuPress={openDrawer} />
      <View style={styles.content}>
        <Text style={styles.sectionTitle}>Analytics</Text>
        
        <View style={styles.metricsRow}>
          <View style={styles.blueCard}>
            <Text style={styles.blueCardLabel}>Total Valuation</Text>
            <Text style={styles.blueCardValue}>${totalValuation.toLocaleString()}</Text>
            <View style={styles.blueCardPill}>
              <Feather name="arrow-up-right" size={12} color="#FFF" />
              <Text style={styles.blueCardPillText}>Live Data</Text>
            </View>
          </View>
          
          <View style={styles.whiteCard}>
            <Text style={styles.whiteCardLabel}>Items Scanned</Text>
            <Text style={styles.whiteCardValue}>{itemsCount}</Text>
            <Text style={styles.whiteCardSub}>Across {estatesCount} estates</Text>
          </View>
        </View>

        <View style={styles.reportCard}>
          <View style={styles.reportHeader}>
            <View style={styles.reportIconWrap}>
              <Feather name="file-text" size={20} color={COLORS.primary} />
            </View>
            <View style={styles.reportInfo}>
              <Text style={styles.reportTitle}>Generate Full Report</Text>
              <Text style={styles.reportSub}>Export PDF of all current inventory</Text>
            </View>
          </View>
          <TouchableOpacity style={styles.downloadBtn} onPress={handleDownloadPDF}>
            <Text style={styles.downloadTxt}>Download PDF</Text>
          </TouchableOpacity>
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: COLORS.bg },
  content: { flex: 1, paddingHorizontal: 20 },
  
  headerContainer: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 20, paddingTop: 60, paddingBottom: 16,
    backgroundColor: COLORS.bg, borderBottomWidth: 1, borderBottomColor: COLORS.border,
  },
  headerBtn: { width: 40, height: 40, borderRadius: 20, borderWidth: 1, borderColor: COLORS.border, justifyContent: 'center', alignItems: 'center', backgroundColor: COLORS.surface },
  headerCenter: { alignItems: 'center' },
  headerTitle: { fontSize: 18, fontWeight: '800', color: COLORS.textDark, letterSpacing: -0.5 },
  headerSubtitle: { fontSize: 11, color: COLORS.textLight, marginTop: 2, fontWeight: '500' },
  headerUserBtn: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 20, backgroundColor: '#EFF6FF', borderWidth: 1, borderColor: '#BFDBFE' },
  onlineDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: COLORS.primary, marginRight: 6 },

  sectionTitle: { fontSize: 22, fontWeight: '800', color: COLORS.textDark, letterSpacing: -0.5, marginTop: 24, marginBottom: 16 },

  metricsRow: { flexDirection: 'row', gap: 12, marginBottom: 16 },
  
  blueCard: { flex: 1, backgroundColor: COLORS.primary, borderRadius: 16, padding: 16, minHeight: 140, justifyContent: 'space-between' },
  blueCardLabel: { color: '#BFDBFE', fontSize: 11, fontWeight: '700' },
  blueCardValue: { color: '#FFF', fontSize: 28, fontWeight: '800', marginVertical: 4 },
  blueCardPill: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.2)', alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12 },
  blueCardPillText: { color: '#FFF', fontSize: 10, fontWeight: '700', marginLeft: 4 },

  whiteCard: { flex: 1, backgroundColor: COLORS.surface, borderRadius: 16, padding: 16, minHeight: 140, justifyContent: 'space-between', borderWidth: 1, borderColor: COLORS.border },
  whiteCardLabel: { color: COLORS.textLight, fontSize: 11, fontWeight: '700' },
  whiteCardValue: { color: COLORS.textDark, fontSize: 28, fontWeight: '800', marginVertical: 4 },
  whiteCardSub: { color: '#94A3B8', fontSize: 11, fontWeight: '500' },

  reportCard: { backgroundColor: COLORS.surface, borderRadius: 16, padding: 16, borderWidth: 1, borderColor: COLORS.border },
  reportHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  reportIconWrap: { width: 40, height: 40, borderRadius: 12, backgroundColor: '#EFF6FF', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  reportInfo: { flex: 1 },
  reportTitle: { fontSize: 14, fontWeight: '800', color: COLORS.textDark, marginBottom: 2 },
  reportSub: { fontSize: 11, color: COLORS.textLight },
  downloadBtn: { width: '100%', paddingVertical: 12, borderRadius: 12, borderWidth: 1, borderColor: COLORS.border, alignItems: 'center' },
  downloadTxt: { color: COLORS.textDark, fontSize: 13, fontWeight: '700' },
});
